name: Deploy to Koyeb
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: nabilcodes/eshop:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Koyeb
        uses: koyeb/koyeb-action@v1
        with:
          api-key: ${{ secrets.KOYEB_API_KEY }}
          app-name: eshop
          image: nabilcodes/eshop:latest
          environment: your-environment-id
