name: Deploy to Koyeb
on:
  push:
    branches:
      - '**'  # Trigger on all branches
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Git Repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Set gradlew as executable
        run: chmod +x ./gradlew
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: nabilcodes/eshop:name-update-v0.1
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Koyeb
        uses: koyeb/koyeb-action@v1
        with:
          api-key: ${{ secrets.KOYEB_API_KEY }}
          app-name: eshop
          image: nabilcodes/eshop:name-update-v0.1
          environment: fdafc804
