name: Deploy to Koyeb
on:
  push:
    branches:
      - '**'  # Trigger on all branches
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Git Repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Set gradlew as executable
        run: chmod +x ./gradlew
      - name: Build JAR
        run: ./gradlew build -x test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t nabilcodes/eshop .
          docker tag nabilcodes/eshop nabilcodes/eshop:name-update-v0.1
          docker push nabilcodes/eshop:name-update-v0.1
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install koyeb CLI
        run: |
          curl -s https://install.koyeb.com | bash
          export PATH=$PATH:$HOME/.koyeb/bin
      - name: Deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: coastal-cod
          service-name: eshop
          service-ports: 8080:http
          build-timeout: 900
          healthy-timeout: 900
          privileged: false
          git-url: github.com/Nabilcodes/eshop
          git-branch: troubleshoot-docker-error
          git-builder: buildpack
          service-instance-type: nano
          service-regions: fra
          service-routes: /:80
          service-type: web
          skip-cache: false


#          image: nabilcodes/eshop:name-update-v0.1
#          environment: fdafc804
