name: Deploy to Koyeb
on:
  push:
    branches:
      - '**'  # Trigger on all branches
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Git Repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Set gradlew as executable
        run: chmod +x ./gradlew
      - name: Build JAR
        run: ./gradlew build -x test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t nabilcodes/eshop .
          docker tag nabilcodes/eshop nabilcodes/eshop:name-update-v0.1
          docker push nabilcodes/eshop:name-update-v0.1
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Koyeb
        uses: koyeb/koyeb-action@v1
        with:
          api-key: ${{ secrets.KOYEB_API_KEY }}
          app-name: eshop
          image: nabilcodes/eshop:name-update-v0.1
          environment: fdafc804
