name: SonarCloud Analysis

on:
  push:
    branches:
      - '**'  # Trigger on all branches

jobs:
  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git Repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Set gradlew as executable
        run: chmod +x ./gradlew
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=nabilcodes
            -Dsonar.projectName=eshop
            -Dsonar.projectKey=Nabilcodes_eshop
            
